# Generated by Django 2.2.5 on 2019-09-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target', models.FloatField()),
                ('daily_FTD', models.FloatField()),
                ('daily_amount', models.FloatField()),
                ('monthly_FTD', models.FloatField()),
                ('monthly_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Representative')),
            ],
        ),
    ]
