# Generated by Django 2.2.5 on 2019-09-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video_key',
        ),
    ]
