# Generated by Django 2.2.5 on 2019-09-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20190921_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='daily_FTD',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='representative',
            name='daily_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='representative',
            name='monthly_FTD',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='representative',
            name='monthly_amount',
            field=models.FloatField(default=0),
        ),
    ]
