# Generated by Django 2.2.5 on 2019-11-18 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20191105_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
